scikit-fuzzy/scikit-fuzzy

- skfuzzy/filters/fire.py
Fixes breakage of `fire2d` from improving the `pad` framework in #31.
> FIX: FIRE filtering now works with new `pad`

- skfuzzy/filters/fire.py
Combine three lines into one, making use of `np.newaxis`.
> FIX: More concise style in FIRE filter

- skfuzzy/filters/fire.py
Follow style guidelines for variable naming within functions. They should exclusively be lower case.
> PEP8: fire.py

- skfuzzy/cluster/_cmeans.py
- skfuzzy/cluster/tests/test_cmeans.py
- skfuzzy/defuzzify/defuzz.py
- skfuzzy/fuzzymath/__init__.py
- skfuzzy/fuzzymath/_continuous_to_discrete.py
- skfuzzy/fuzzymath/fuzzy_ops.py
- skfuzzy/fuzzymath/tests/test_fuzzy_ops.py
- skfuzzy/image/imops.py
- skfuzzy/image/metrics.py
- skfuzzy/intervals/intervalops.py
This is a major improvement to the API - all functions now expose purely lowercase variables. In most cases this will be a transparent improvement.
**Notable changes which may affect legacy code**
* The `U_init=` kwarg in `cmeans` has changed. It is now just `init=`.
* The function `partial_dMF` is now named `partial_dmf`.
> STY: Overhaul package to follow PEP8 capitalization conventions

- README.md
As this package is now on PyPi, the README definitely needs to be updated!
> DOC: Update README with new pip install instructions.

- docs/examples/README.txt
- docs/examples/plot_tipping_problem.py
This is a step-by-step walkthrough for using Scikit-Fuzzy and NumPy to solve the classic tipping problem.
Wrap this up into a function or class, and it's easy to recalculate on demand for various inputs e.g. in a control system.
> DOC: Add tipping problem example to Gallery

- .gitignore
- CONTRIBUTING.txt
- TASKS.txt
- docs/Makefile
- docs/source/contents.txt
- docs/source/contribute.txt
- docs/source/documentation.txt
- docs/source/index.txt
- docs/source/install.txt
- docs/source/user_guide.txt
- docs/source/userguide/getting_started.txt
- skfuzzy/intervals/intervalops.py
From nearly 30 warnings to zero, and a much better build of the documentation to boot!
> DOCFIX: Sphinx now runs without errors

- skfuzzy/cluster/_cmeans.py
- skfuzzy/control/control.py
- skfuzzy/defuzzify/defuzz.py
- skfuzzy/filters/fire.py
- skfuzzy/fuzzymath/fuzzy_ops.py
- skfuzzy/membership/generatemf.py
Improvements to docstring formatting for docscrape to properly pick up and autoformat the API docs.
> DOC: Fix docstrings so docscrape works properly.

- docs/examples/plot_cmeans.py
Finally, an example illustrating use of `cmeans` and `cmeans_predict`!
> DOC: Add formal example detailing use of Fuzzy c-means

- README.md
Improve `README` file of the library.
> Add link to the documentation in readme

- docs/Makefile
- docs/examples/plot_tipping_problem.py
- docs/examples/plot_tipping_problem_newapi.py
- docs/make.bat
- docs/source/user_guide.txt
- docs/source/userguide/fuzzy_control_primer.txt
This addresses some of #77 
Please review and change as needed.  Especially need to double-check the links between the two new pages are done correctly.  Also, not sure how to actually publish to pythonhosted's website.
> DOC: Update pythonhosted documentation

- docs/source/conf.py
We're generating some nice logos - they should be used!
> DOC: Use scikit-fuzzy logo as favicon

- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/visualization.py
Minor fixes and improvements to the fuzzy control system visualization infrastructure.
> FIX: .view() works as expected.

- README.md
Minor documentation update in advance of 0.2
> DOC: Update public README with NetworkX dependency.

- docs/examples/plot_control_system_advanced.py
- docs/examples/plot_tipping_problem_newapi.py
Adds a new example with a much more complicated fuzzy system, illustrating design of a non-trivial fuzzy system. This example also uses a number of more advanced optional features, such as control of cache flushing and viewing the control surface.
> Advanced control system example

- skfuzzy/cluster/_cmeans.py
> DOC: Warn about high dimensionality FCM clustering w/Winkler ref.

- skfuzzy/membership/generatemf.py
> DOC: Update membership generation docs.

- skfuzzy/control/visualization.py
Docstring enhancements, documenting the improvements in #133.
> DOC: Update/enhance .view docstrings.

- skfuzzy/__init__.py
Major point release includes significant performance improvements for interpolation - by far the largest prior bottleneck.  Those running up against CPU limitations may see 2-3+ orders of magnitude improvements.
There have been also some more minor improvements, particularly to documentation and improvements in how the visualization framework operates in `skfuzzy.control`.
> RELEASE: Version 0.3

- skfuzzy/__init__.py
Maintenance change to package versioning.
> DEV: Start 0.4 development

- .travis.yml
- skfuzzy/defuzzify/tests/test_defuzz.py
- skfuzzy/membership/generatemf.py
- skfuzzy/membership/tests/test_generatemf.py
> FIX: Correct Gaussian membership formula.

- docs/examples/plot_tipping_problem_newapi.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/rule.py
Closes all issues described in #144.
> FIX: Fix Rule.view() and print_state Py3.x compat.

- docs/examples/plot_tipping_problem.py
- docs/examples/plot_tipping_problem_newapi.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/tests/test_controlsystem.py
> DOC/TST: Fix bounds checking

- skfuzzy/control/controlsystem.py
- skfuzzy/control/rule.py
- skfuzzy/control/visualization.py
Added the function view_n() in rule and the necessary changes in controlsystem and visualization in order to see the names of the dots in the diagram and also if the MF is being used by the rules.
> Added the function view_n() in rule

- skfuzzy/__init__.py
- skfuzzy/image/arraypad.py
Fixing a typo and a few minor errors.
Not sure why these are not affecting github builds - probably there is some ordering involved.
> Fixing doctest errors.

- skfuzzy/fuzzymath/fuzzy_logic.py
- skfuzzy/fuzzymath/fuzzy_ops.py
I try my best to restore the docstrings.
Continue to PR#171
> Restore the docstrings, continue to PR#171

- skfuzzy/control/rule.py
> DOCFIX: Harmonize Consequent documentation for Rules.

- .travis.yml
- skfuzzy/control/antecedent_consequent.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/rule.py
- tools/build_versions.py
Replace the use of some methods that are no longer supported in NetworkX v2 and fix some issues with the CI setup.
> Replace use of methods that are no longer supported in NetworkX v2.

- docs/examples/plot_tipping_problem_newapi.py
Fixing this line the example works fine with Py3 on my environment, and I get the graphs generated successfully. :+1: 
Thanks
Bruno
> Fix tipping problem new api example to work with py3

- docs/Makefile
- docs/ext/docscrape.py
- docs/ext/notebook_doc.py
- docs/ext/numpydoc.py
- docs/ext/plot2rst.py
- docs/ext/plot_directive.py
- docs/source/conf.py
- docs/tools/build_modref_templates.py
- docs/tools/plot_pr.py
Docs now can be built on Python 2.7 with scikit-image 0.14.1 and Sphinx 1.8.
Python 3.x still has some lingering issues, but the docs at least can now be built.
> DOC: Overhaul doc build to work with Sphinx 1.8.

- docs/Makefile
- docs/ext/numpydoc.py
- docs/ext/plot2rst.py
Fix some issues with building the docs with Python 3.
> fix: Docs building issues.

- .github/workflows/main.yml
- Makefile
- docs/source/conf.py
Minor quality-of-life update for those working on Linux/OSX and prefer to use the Makefile for testing.
> Fix Makefile for test and coverage using pytest.

- skfuzzy/membership/__init__.py
- skfuzzy/membership/generatemf.py
- skfuzzy/membership/tests/test_generatemf.py
Resurrected manually through diffs as so much has changed since this older PR, in order to run thru CI.
Supersedes and closes #268 
Thanks to @jasper-vdm for the original code, and apologies for the long road to getting merged - @jasper-vdm and @wouter-vdb you can update your forks now ;)
> Bring forward PR #268 with fix to piecemf and new piecewise membership funcs.

- skfuzzy/__init__.py
Update the version tag for release.
> RELEASE: Version 0.5.0

- pyproject.toml
This will build a universal wheel in addition to the source distribution.
> BUILD: Update pyproject.toml to request universal wheel.
