- skfuzzy/filters/fire.py
- skfuzzy/filters/tests/test_fire.py
Full test coverage in `skfuzzy.filters` and enhancement to make the `fuzzyresolution` kwarg usable in `fire2d`.
> TST/ENH: FIRE tests and `fuzzyresolution` fully functional in fire2d

- setup.py
Seeing as we now have a stable 0.1.1 release as of #39, the repo needs to move on!
> DOC: Change version of source checkout to 0.2dev

- docs/Makefile
- docs/source/conf.py
- docs/source/index.txt
- docs/source/overview.txt
The doc build changes in #43 made Sphinx lose track of the API documentation. That's a problem, since right now the majority of the documentation *is* the API documentation. On my system this wasn't apparent because the old cache was being used in subsequent builds, but after a `make clean` suddenly no API docs could be found.
These changes fix that. Along for the ride: adding the `api` target to the Makefile .PHONY and improving the Overview page.
> FIX: Fix the doc build to actually include the API docs

- skfuzzy/fuzzymath/fuzzy_ops.py
This sentence wasn't grammatically correct. Fixed.
> DOCFIX: Correct verbiage in interp_membership note

- skfuzzy/defuzzify/__init__.py
- skfuzzy/defuzzify/defuzz.py
- skfuzzy/defuzzify/tests/test_defuzz.py
Satisfies #48 - take a look @pbreach!
A fast and efficient method to detect an arbitrary number of cuts was simple to implement with convolution, then slightly tricky to make robust at edges. Symmetric padding by two elements should not materially affect the runtime of this routine.
This implementation **only** reports boundaries *that actually cross the lambda cut value within the provided membership function*. If one edge of a membership function was 0.3, a lambda cut value of 0.2 would not report the final value as a boundary. Put differently, it makes absolutely no assumptions about the membership function outside the provided discrete range.
> Fix lambda_cut with lcut=1 and add lambda_cut_boundaries function.

- skfuzzy/defuzzify/defuzz.py
Minor fix. This hidden helper function is gated such that the check is impossible to trigger, so it is removed.
> TST: Remove unnecessary check, coverage again 100% in defuzz.py

- skfuzzy/image/imops.py
The first of several PRs to fix the doc build and squash Sphinx warnings.
Down to 26 warnings from 38!
> DOC: Fix docstring formatting for defocus_local_means

- skfuzzy/image/arraypad.py
Personalize the `pad` docstring for `scikit-fuzzy`.
> DOC: Fix `pad` docstring and examples

- skfuzzy/intervals/intervalops.py
Fixes a regression in the Dong, Shah, and Wong (DSW) fuzzy arithmetic functions introduced in #39, where all internal variables were made lowercase to satisfy PEP8. The distinction between `FF` and `ff` is restored without resorting to capital variables.
> FIX: Regression in DSW mathematics introduced by capitalization changes.

- skfuzzy/cluster/_cmeans.py
- skfuzzy/defuzzify/defuzz.py
- skfuzzy/filters/fire.py
- skfuzzy/fuzzymath/fuzzy_ops.py
- skfuzzy/intervals/intervalops.py
Fixes a number of Sphinx reference issues, revise or clarify a few docstrings, and redirect users to the `dsw_*` functions using interval-based arithmetic if the output from `fuzzy_*` mathematics are not expected.
> DOCFIX: Resolve errors in Sphinx build and improve docstrings.

- setup.py
This should fix a rare installation issue raised on the mailing list by Ariel Kenneth Ampol, where the `install_package_data` kwarg was unrecognized by distutils.
> FIX: Specify package data differently

- setup.cfg
- setup.py
* URL added, points to PyPi
* Secure `https://` links used throughout
* Minor tightening of the grammar in the package description
* Added `*.md` to the data files which should be included with each distribution and a minimal `setup.cfg` file to specify `README.md` is the description file.
> ENH: Add URL, use secure links, include README.md with distribution

- DEPENDS-docs.txt
- docs/Makefile
- docs/ext/plot2rst.py
- docs/tools/build_modref_templates.py
- requirements-docs.txt
Docs now build with zero warnings for me on Sphinx 1.3.1, using latest Python 2.7.x environment from Anaconda. Closes #62.
Can you confirm this resolves the problem, @erasche?
I'll upload to readthedocs tomorrow.
> DOCFIX: Fix doc build for Sphinx >= 1.3

- CONTRIBUTORS.txt
- docs/examples/plot_tipping_problem.py
The second argument of np.max is the axis, so np.max() on this example
was returning the first argument instead of the maximum between both.
> Looks like a typo: max() instead of fmax().

- docs/examples/plot_tipping_problem.py
The example result is the same, but these membership functions were misidentified (which carried through to figure legends).
Hopefully this makes the example easier to follow.
> DOCFIX: Low/high membership functions transposed.

- TASKS.txt
- docs/source/_static/docversions.js
- docs/source/conf.py
- docs/source/index.txt
- docs/tools/apigen.py
- skfuzzy/image/shape.py
This PR fixes a few places, mostly in the docs, where mentions of `skimage` remained after borrowing the doc build from scikit-image. They are now converted to `skfuzzy`; I believe none remain out of place.
Also a few PEP8 fixes.
> DOC: Harmonize skfuzzy branding.

- .gitignore
- example.py
- skfuzzy/control/__init__.py
- skfuzzy/control/antecedent_consequent.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/rule.py
- skfuzzy/control/state.py
- skfuzzy/control/tests/test_controlsystem.py
- skfuzzy/control/tests/test_fuzzyvariables.py
- skfuzzy/control/visualization.py
This is an improvement to the rules API to use operators for rules:
- `&` for and
- `|` for or
- `~` for not
I've tested it with some pretty complex logic and it seems to work well.  This isn't in an end state, but I feel like enough is done to submit for PR for feedback.
> Improve Rules API

- skfuzzy/control/controlsystem.py
Bug reported by @nilayrox18:
Requires python 3 to reproduce:
```python
import numpy as np
import skfuzzy as fuzz
quality = fuzz.Antecedent(np.arange(0,11,1),'quality')
service = fuzz.Antecedent(np.arange(0,11,1),'service')
tip = fuzz.Consequent(np.arange(0,26,1),'tip')
quality.automf(3)
service.automf(3)
tip.automf(3)
quality.view()
service.view()
tip.view()
rule1 = fuzz.Rule(quality['poor'] | service['poor'],tip['poor'])
rule2 = fuzz.Rule(quality['good'] | service['good'],tip['good'])
tip_cnt = fuzz.ControlSystem([rule1, rule2])
tipp = fuzz.ControlSystemSimulation(tip_cnt)
tipp.input['quality'] = 5.
tipp.input['service'] = 2.
tipp.compute()
print(tipp.output)
```
Error message is:
Traceback (most recent call last):
File "C:\Users\DarkEvill\Desktop\ex3456.py", line 29, in 
tipp.compute() …
> Fix Python 3 bug from nilayrox18

- skfuzzy/cluster/_cmeans.py
- skfuzzy/filters/fire.py
- skfuzzy/intervals/intervalops.py
A number of docstrings had an underscore after a bracketed, numbered reference on the first line. Sphinx doesn't like this in the first line; everywhere else it's correct, but in the first line you get these warnings.
Minor tweaks to make things a little more imperative.
The doc build should now be completely clean without any warnings.
> DOCFIX: Resolve Sphinx refernce warnings in doc build.

- docs/examples/plot_tipping_problem_newapi.py
- docs/source/userguide/fuzzy_control_primer.txt
- docs/source/userguide/getting_started.txt
Fixes three broken links. Up one level is all that's required to link between sections of the HTML docs.
> DOCFIX: Fix broken relative links between pages.

- DEPENDS.txt
- MANIFEST.in
- docs/source/conf.py
- docs/tools/build_modref_templates.py
- setup.py
- skfuzzy/__init__.py
Pip installation should no longer ever result in a broken installation due to permissions issues around `version.py`.
Thanks to troubleshooting this issue on Windows and a few false starts, the PyPI version bumped from 0.1.3 to 0.1.9 tonight.
Closes #87.
> FIX: Pip installation succeeds regardless of permissions

- skfuzzy/control/controlsystem.py
- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/rule.py
- skfuzzy/control/tests/test_fuzzyvariables.py
- skfuzzy/control/visualization.py
Functionally the most important change is naming `WeightedConsequent` -> `WeightedTerm`, and `FuzzyVariableTerm` became `Term`. Given how these worked and what they required, this reflects their actual function.
Lots more docstrings and style improvements. This addresses in large part #77, but there is still room for some improvement. Improved `view` for Terms so the legend reflects the bold, active membership function.
Also, the tests should now pass! 
What I consider blocking before 0.2 release:
What do you think, @jsexauer?
> New API cleanup

- skfuzzy/control/controlsystem.py
- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/rule.py
- skfuzzy/control/state.py
- skfuzzy/control/tests/test_controlsystem.py
- skfuzzy/control/visualization.py
Closes #91.
Take a look, @jsexauer - I made some significant tweaks to the `StatePerSimulation` and `_InputAcceptor` to make this possible. In essence:
* `ControlSystemSimulation` objects now carry a `unique_id` property based on the `ControlSystem` object `id` and a hash of the current input values in an OrderedDict. If the underlying simulation doesn't change, this is unique to a given set of inputs. If the user sets the inputs back to a particular set of values, this is repeatable, which paves the way for caching (not yet fully implemented)
* All input data is stored and referenced via this unique ID instead of weak references to the simulation object. Dictionaries should stay small enough with ~32 char string keys that weakref shouldn't be needed, but a periodic flush might be …
> Repeated simulations

- skfuzzy/control/controlsystem.py
This partially addresses #82. I'd like to have a way to track the set of input values on each `FuzzyVariable`'s universe which are "covered" by each `Rule` as they get added to the system. Then we could tell the user where their rules have gaps, instead of just telling them to check their work.
However, the error raised in a situation where the inputs do not fire any Terms is now much more informative. It's acceptable at this point to ship 0.2.
> DOC: Make system too sparse error more informative.

- docs/examples/plot_tipping_problem_newapi.py
- docs/tools/build_modref_templates.py
- skfuzzy/control/antecedent_consequent.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/rule.py
- skfuzzy/control/state.py
- skfuzzy/control/term.py
- skfuzzy/control/tests/test_controlsystem.py
- skfuzzy/control/visualization.py
- skfuzzy/defuzzify/tests/test_defuzz.py
- skfuzzy/fuzzymath/tests/test_fuzzy_ops.py
This is a combination of several fixes which have been in the pipeline for 0.2.
* Multiple Rules may now point at the same Consequent, closing #108.
* New `flush_after_run` kwarg added to `ControlSystemSimulation`, allowing a given system to be 'sized to fit' memory by users.
* Caching now defaults on (`cache=True`), because memory can be controlled by setting `flush_after_run`.
* All infrastructure associated with Terms refactored into a separate file, `term.py`, and imports adjusted accordingly.
* Test suite improvements with regression tests for #108 and additional coverage.
* Documentation improvements.
> New API cleanup and fix for #108

- .travis.yml
NumPy / SciPy have a strange error with this portion of the test matrix. Almost nobody on the 3.x branch is using 3.3 or earlier, so this PR drops Python 3.3 from the test matrix.
> Drop testing on Python 3.3

- skfuzzy/control/controlsystem.py
Cached `Antecedent` inputs weren't being cleared. This caused the memory leak reported in #119.
> FIX: Fix memory leak on repeated simulations. Closes #119.

- skfuzzy/fuzzymath/fuzzy_ops.py
Currently, a value out of the range of the set will throw an error as line x[x <= xx][-1] in the interp_membership function returns an empty list. (The value being compared is not in the range of the 1D array denoted by x)
This particular change will circumvent that issue and return 0.0 indicating that the membership is 0 for that set.
> Incorporates out of range values

- .travis.yml
Should fix the recent Travis CI errors, which were due to the latest major release of Pillow ending Python 2.6.x compatibility.
Eventually we will also EOL 2.6, but for now using an older Pillow for this build in the test matrix is simple enough.
> TSTFIX: Pillow 4.x incompatible with Python 2.6.x

- skfuzzy/control/__init__.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/rule.py
- skfuzzy/control/term.py
Instead of having the fuzzy aggregation methods hidden in `rule0.aggregation_method.and_agg_func`, these make them directly accessible to the user by the Rule properties `and_func` and `or_func`.  There is also the option to define them upon Rule creation, with new kwargs.
A new function is available in `skfuzzy.control`: `mult`.  This simply multiples the floating point inputs, and is suitable to replace the default `and_func` which is the Python builtin `min`.
> FEAT: Expose AND/OR aggregation methods to the user.

- skfuzzy/fuzzymath/fuzzy_ops.py
- skfuzzy/fuzzymath/tests/test_fuzzy_ops.py
#128 got me thinking, @katanachan, that `interp_membership` could probably be done more efficiently.  I didn't like all the fancy indexing lookups. 
Turns out that yes, indeed, NumPy has a built-in function to do this.  Including for many values at once, not just one.  The performance improvement is substantial, and it simplifies the code base.
> ENH: Directly use np.interp, 2-3 orders of magnitude faster.

- skfuzzy/control/visualization.py
Previously only the figure was returned.  Now both the figure and axis objects are returned, which is more consistent and extensible.
> ENH: Return both figure and axis for ControlSystemVisualizer

- README.md
First way to cite scikit-fuzzy is via Zenodo DOI directly as software.  
Formal research paper is in preparation, until that time please directly cite the software.
> DOC: Add Zenodo DOI for package to Readme, paper in preparation.

- skfuzzy/control/antecedent_consequent.py
- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/tests/test_fuzzyvariables.py
Hi, I was searching a bit how I could set a different defuzzyfication method in the Consequent, and I couldn't find this in the docs. After digging a bit, I found that it was done simply by passing the `defuzzify_method` in the instantiation. 
So I thought that this may help out other people (I'm not sure, but I believe that if someone do a "search" in the docs, it will appear this in the FuzzyVariable).
If you believe it's handy, I can also add this to the Consequent's doc.
> Add docs for 'defuzzify_method' as a parameter in FuzzyVariable

- skfuzzy/control/controlsystem.py
- skfuzzy/control/tests/test_controlsystem.py
This is an initial attempt at fixing #149, which arises from the changes in NetworkX 2.0.  It works well on the systems I've tested it against, but there are a few failing tests (skipped for now).
When going to compute the system, the `rules` are being returned in a different order than provided by the user.  It appears this may be in opposite order; it bears additional investigation.  
If anyone finds a system which worked under NetworkX 1.x but suddenly starts complaining about loops in the graph with this fix in place after upgrading to NetworkX 2.x, please share it.  That's how this could fail, and it would be invaluable to fixing the problem.
> FIX: NetworkX 2.0 forward compatibility

- skfuzzy/__init__.py
- skfuzzy/control/tests/test_controlsystem.py
This minor point release brings a significant new feature and minor fixes/compatibility enhancements:
Major feature:
* Arrays are now accepted as system inputs; all inputs must have the same shape.  The output matches this shape.  This is dramatically more computationally efficient for repeated runs on existing data - within the limits of your system memory. (see #141)
Minor fixes
* Fixed the mathematical definition of `skfuzzy.gaussmf`; this is a potentially breaking change but the results are now correct (see #147)
* NetworkX 2.0 forward compatibility (see #149 and #150)
* Improve and harmonize the `.view()` methods in `skfuzzy.control` (see #142 and #148)
* Update examples to use the above
> Minor point release - 0.3.1

- skfuzzy/cluster/_cmeans.py
- skfuzzy/cluster/normalize_columns.py
- skfuzzy/cluster/tests/test_cmeans.py
- skfuzzy/cluster/tests/test_normalize_columns.py
`cmeans` and `cmeans_predict` fail for values of `m` close to 1, for example 1.0001 [at this point in the code.](https://github.com/99991/scikit-fuzzy/blob/52a53157a0d42833a8a0277d59ca61c0de7df392/skfuzzy/cluster/_cmeans.py#L33)
It will expand to `d**-20000` which explodes for `d < 1`.
With some logarithms and exps this can be fixed, but comes at the cost of two to three times slower execution, so I made this enhancement optional. It can be enabled by passing `safe=True` to `cmeans` and `cmeans_predict`.
> Numerically safe normalization of columns exponentiated to large powers.

- skfuzzy/cluster/_cmeans.py
It is not necessary to compute this outer product. Each row of the matrix will be divided elementwise by the vector.
> ENH: Remove unnecessary computation of an outer product

- skfuzzy/cluster/_cmeans.py
Add other metrics to compute cmeans.
The metric is set to euclidean by default, so that it will not raise new issue for users.
The new option is "metrics", and we can use any distance from Scipy.spatial.distance.cdist.
Possible Improvement:
- have an error message if the cmeans and cmeans_predict use different metrics
> [link to issue #159] - add other metrics

- skfuzzy/defuzzify/defuzz.py
- skfuzzy/defuzzify/tests/test_defuzz.py
This is a minor edit for issue #188: the lom/som defuzzification calculations used to apply abs() to their index sets, leading to a problem with all-negative universes.  
Fixed their definition to look more like the mom defuzzification method, and augmented the test-cases to include one with all-negative universes.
James.
> Fixed lom/som for negative ranges

- setup.py
pipenv fails to install `scikit-fuzzy` on a clean environment with the following error:
```bash
$ pipenv install scikit-fuzzy
Installing scikit-fuzzy…
Collecting scikit-fuzzy
Using cached https://files.pythonhosted.org/packages/09/36/4938f22f99ea415ef6b9f831b36057e1cb6bac3783f35a54a99da97eb5ff/scikit-fuzzy-0.4.0.tar.gz
Complete output from command python setup.py egg_info:
To install scikit-fuzzy from source, you will need numpy.
Install numpy with pip:
pip install numpy
Or use your operating system package manager.
----------------------------------------
Error:  An error occurred while installing scikit-fuzzy!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ojxdtv4u/scikit-fuzzy/
This is likely caused by a bug in scikit-fuzzy. Report this to its …
```
> Solve problems with pipenv

- skfuzzy/control/controlsystem.py
This small patch resolves #202.
However, in testing something in Python 3.7 has resulted in significant performance regression related to prior versions.  The test suite prior to this patch and with this patch runs in about 1.8 seconds on this laptop, on Python 3.6 and prior.  Under Python 3.7 the suite takes 2.8 seconds, and the entire increase in runtime is related to the complex system test.
Because the performance with the patch is unaffected in Python 3.6, this major performance regression was introduced with Python 3.7 specifically.  Please take note of this; if performance is important, users should remain on Python 3.6.
> FIX: Python 3.7 compatibility with PEP 479.

- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/tests/test_fuzzyvariables.py
Closes #140 with additional logic and checks.  The `number` is now arbitrary (though obviously only integer) and if not 3, 5, or 7 a check is made if the user provided an iterable of `names` with length equal to `number`.
> ENH: Relax restriction on number of mfs in automf.

- skfuzzy/control/controlsystem.py
This happens because PEP 479 made a change to generators: when StopIteration is raised inside a generator, it is replaced with RuntimeError when the exception is about to bubble out of the generator. This behaviour is not backwards compatible and was slowly introduced with this transition plan.
> To promote compatibility with version 3.7 of python

- skfuzzy/image/__init__.py
Replacing two tabs in skfuzzy.image.__init__.py (only two found, everything else using spaces)
> Use spaces, not tabs

- .gitignore
- .travis.yml
- skfuzzy/control/controlsystem.py
- skfuzzy/control/tests/test_controlsystem.py
- skfuzzy/control/tests/test_crisp_value_calculator.py
- skfuzzy/control/tests/test_terms.py
- tox.ini
An input value for a fuzzy control system simulation can now be a (valid) term label, in which case the membership value for that term will be set to 1 (and 0 for the others). This can be useful when, for example, the input is obtained by means of a user interface in which the user can make a convenient/meaningful choice by picking one of the terms instead of having to provide a concrete value from some arbitrary universe.
> Feature: Accept term labels as input values in a control system simulation.

- skfuzzy/control/__init__.py
- skfuzzy/control/controlsystem.py
- skfuzzy/control/exceptions.py
- skfuzzy/control/fuzzyvariable.py
- skfuzzy/control/tests/test_controlsystem.py
- skfuzzy/defuzzify/__init__.py
- skfuzzy/defuzzify/defuzz.py
- skfuzzy/defuzzify/exceptions.py
The objective is to provide the option to gracefully deal with sparse rules in a control system simulation. When one out of x applicable rules is sparse then the base behaviour is to raise an exception (and thus apply none). With this `lenient` option, the sparse rule will be ignored and the others will be applied. The included test demonstrates this behaviour.
> Lenient simulation

- skfuzzy/fuzzymath/_continuous_to_discrete.py
Minor fix due to recent Scipy removal of the deprecated `scipy.linalg.pinv2` in favor of `pinv`.
This should also be backwards compatible.
> MAINT: Scipy removed `pinv2`, in favor of `pinv`

- docs/Makefile
Gitwash had a bug where the default URL still used `git://` to access its repo.  This was the cause of our GH Actions failures, which *should* now be resolved.  I've submitted a PR over there to fix it for anyone else, but directly specifying the `--gitwash-url` should fix it here immediately and durably.
Supersedes #288.  Cleanup after #280.  
Pinging @balins - thanks again for your help migrating to GH Actions and fingers crossed the suite should (finally) be green!
> Gitwash test

- skfuzzy/control/tests/_skipclass.py
- skfuzzy/control/tests/test_controlsystem.py
- skfuzzy/fuzzymath/fuzzy_ops.py
- skfuzzy/image/tests/test_imops.py
- skfuzzy/image/tests/test_pad.py
numpy 1.25 removed a lot of their nose helpers. This PR copies over one of the ones we were using and stops calling another method that was removed.
I think that long term, `nose` should be phased out. I could also work on that approach to, though this is the simplest fix that I could think of that I'm going to for now apply in [nixpkgs](https://github.com/NixOS/nixpkgs) to fix this package there.
> Adapt tests to numpy 1.25

- skfuzzy/image/__init__.py
Using `distutils` version classes are deprecated and is recommended to use `packaging.version`.
> Fix deprecation warning with `distutils`

- .github/workflows/main.yml
- skfuzzy/control/rule.py
- skfuzzy/control/tests/_skipclass.py
Nose is unsupported and broken starting in 3.10.  
This is a temporary stopgap measure until the test suite is converted to `pytest`; see #302.
> TSTFIX: Temporarily limit test matrix to 3.9

- .github/workflows/main.yml
- CONTRIBUTING.txt
- DEPENDS-tests.txt
- docs/ext/docscrape.py
- docs/ext/notebook_doc.py
- docs/ext/numpydoc.py
- docs/ext/plot2rst.py
- docs/ext/plot_directive.py
- ruff.toml
- setup.cfg
- skfuzzy/__init__.py
- skfuzzy/control/tests/test_terms.py
- tools/build_versions.py
- tox.ini
[Ruff](https://beta.ruff.rs/) supports [over 600 lint rules](https://beta.ruff.rs/docs/rules) and can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus dozens of plugins), [isort](https://pypi.org/project/isort/), [pydocstyle](https://pypi.org/project/pydocstyle/), [yesqa](https://github.com/asottile/yesqa), [eradicate](https://pypi.org/project/eradicate/), [pyupgrade](https://pypi.org/project/pyupgrade/), and [autoflake](https://pypi.org/project/autoflake/), all while executing (in Rust) tens or hundreds of times faster than any individual tool.
`ruff --format=github` rapidly provides intuitive GitHub Annotations to contributors.
> Lint Python code with ruff instead of flake8

- docs/ext/docscrape.py
- docs/ext/plot2rst.py
- ruff.toml
% `ruff --select=W605 --fix . ` # https://beta.ruff.rs/docs/rules/invalid-escape-sequence
```
Found 14 errors (14 fixed, 0 remaining).
```
% `ruff rule W605`
Derived from the **pycodestyle** linter.
Autofix is always available.
Checks for invalid escape sequences.
Invalid escape sequences are deprecated in Python 3.6.
```python
regex = "\.png$"
```
Use instead:
```python
regex = r"\.png$"
```
- [Python documentation: String and Bytes literals](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals)
> ruff rule W605: Fix invalid escape sequences

- docs/source/index.txt
Removes the link to a missing page in table of contents.
Closes #321
> Remove spurious ToC link in doc build to nonexistant page.

- skfuzzy/fuzzymath/fuzzy_logic.py
This occurred due to floating point error in specific edge cases. The result would have been missing the far expected max value, after operations which used `_resampleuniverse`. The bug has existed since the package was introduced. This will break some behavior but is absolutely a bugfix.
HOWEVER!  `skfuzzy.control` uses a different approach to this operation which is more efficient and importantly is correct. This will not change the behavior of systems in production using systems defined through the `skfuzzy.control` API.
Bug report and code to reproduce in #320. Credit to @fabrizioruffini for finding this.
Closes #320.
> Fix longstanding error which occasionally eroded universes in classic API

- .gitignore
Add *.ipynb to .gitignore
Minimal quality of life improvement for any developers working with iPython/Jupyter notebooks in the package.
> STY: Ignore .ipynb files which may exist in the package.

- skfuzzy/cluster/_cmeans.py
Previously the maximum iteration argument `maxiter` actually terminated iteration one loop too early.
Closes #289
> FIX: Correct limit on `maxiter`
